---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-port
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ .Values.container.ports.porthttp }} 
      targetPort: {{ .Values.container.ports.targethttp }} 
    - name: slave
      port: {{ .Values.container.ports.portjnlp }} 
      targetPort: {{ .Values.container.ports.targetjnlp }} 
  selector:
    app: {{ .Values.name }}