---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-port
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ .Values.container-ports.http-port }} 
      targetPort: {{ .Values.container-ports.http-port }} 
    - name: slave
      port: {{ .Values.container-ports.jnlp-port }} 
      targetPort: {{ .Values.container-ports.jnlp-port }} 
  selector:
    app: {{ .Values.name }}