---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-port
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ .Values.ports.master.port }} 
      targetPort: {{ .Values.ports.master.targetPort }} 
    - name: slave
      port: {{ .Values.ports.slave.port }} 
      targetPort: {{ .Values.ports.slave.targetPort }} 
  selector:
    app: {{ .Values.name }}