---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service-port
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ .Values.container.ports.httpport }} 
      targetPort: {{ .Values.container.ports.httpport }} 
    - name: slave
      port: {{ .Values.container.ports.jnlpport }} 
      targetPort: {{ .Values.container.ports.jnlpport }} 
  selector:
    app: {{ .Values.name }}