namespace: ci-cd-helm
name: jenkins-helm
image: jfrog.it-academy.by/public/jenkins-ci:igolubovich
mail: igor.golubovich.1991@gmail.com


spec:
  ports:
   master:
      port: 8080
      targetPort: 8080
   slave:
      port: 50000 
      targetPort: 50000 


resources: 
 requests:
   cpu: 1000m
   memory: 1000Mi
 limits:
   cpu: 2300m
   memory: 2300Mi

nfs:
 server: 192.168.37.105
 path: /mnt/IT-Academy/nfs-data/sa2-20-22/Igor_Golubovich/jenkins-helm

ingress:
 class: nginx
 host: jenkins-helm.k8s-17.sa
 alias: jenkins-helm.k8s-18.sa
 port: 8080
  