namespace: ci-cd-helm
# name: jenkins-helm
image: jfrog.it-academy.by/public/jenkins-ci:igolubovich
mail: igor.golubovich.1991@gmail.com


service:
 master:
    port: 8080
    targetPort: 8080
 slave:
    port: 50000 
    targetPort: 50000 

resources: 
 requests:
   cpu: 1100m
   memory: 1100Mi
 limits:
   cpu: 2200m
   memory: 2200Mi

nfs:
 server: 192.168.37.105
 path: /mnt/IT-Academy/nfs-data/sa2-20-22/Igor_Golubovich/jenkins

ingress:
 class: nginx
 host: jh.k8s-17.sa
 alias: jh.k8s-18.sa
 port: 8080
  